package com.generics;
/*
  When compiling a class or interface that extends a parameterized class or implements a
  parameterized interface, the compiler may need to create a synthetic method, called a 
  bridge method, as part of the type erasure process. You normally don't need to worry 
  about bridge methods, but you might be puzzled if one appears in a stack trace.
 */
public class BridgeMethodsinGenerics {

}

 class Node {

    public Object data;

    public Node(Object data) { this.data = data; }

    public void setData(Object data) {
        System.out.println("Node.setData");
        this.data = data;
    }
}

 class MyNode extends Node {

    public MyNode(Object data) {
		super(data);
	}

	// Bridge method generated by the compiler
    public void setData(Object data) {
        setData((Integer) data);
    }

    public void setData(Integer data) {
        System.out.println("MyNode.setData");
        super.setData(data);
    }

    // ...
}
